#pragma once

const int MAP_SQUARE_PIXEL_SIZE = 32;
const int WINDOW_WIDTH = 640, WINDOW_HEIGHT = 496;
const int ACTION_BAR_HEIGHT = 100;
const int MAP_VIEW_WIDTH = WINDOW_WIDTH, MAP_VIEW_HEIGHT = WINDOW_HEIGHT - ACTION_BAR_HEIGHT;
